name: build, test, deployment

on: [push, pull_request]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Package
        run: mvn clean package
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Maven Test
        run: mvn clean test
  deployment:
    name: Deploy helm chart
    runs-on: 'ubuntu-latest'
    needs: [Build]
    steps:
    - name: 'Checkout'  # Checkout the repository code.
      uses: 'actions/checkout@v1'
    - name: 'Deploy'
      uses: 'deliverybot/helm@master'
      with:
        token: '${{ github.token }}'
        release: 'myapp'
        chart: './helm/app'
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
  # docker:
  #   name: Publish Docker Image
  #   runs-on: ubuntu-latest
  #   needs: [Build]
  #   env:
  #     REPO: ${{ secrets.DOCKER_REPO }}
  #   steps:
  #     - uses: actions/checkout@v1
  #     - name: Docker Hub Sign-in
  #       run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
  #     - name: Building Docker Image
  #       run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} .
  #     - name: Publish Docker Image
  #       run: docker push $REPO

